"""empty message

Revision ID: 24f83257e0ce
Revises: f1d5c5b4862a
Create Date: 2026-03-09 15:08:34.787639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f83257e0ce'
down_revision = 'f1d5c5b4862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_frog_attempt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('frog_game_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('frog_game_done')
        batch_op.drop_column('has_frog_attempt')

    # ### end Alembic commands ###
