"""empty message

Revision ID: 2dbe5ebf52a0
Revises: c10f3f2f8ee2
Create Date: 2026-04-01 10:03:03.131129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbe5ebf52a0'
down_revision = 'c10f3f2f8ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('channel_subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('channel_subscription_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_subscription_pkey'))
    )
    op.drop_table('channel_sub')
    # ### end Alembic commands ###
