"""empty message

Revision ID: 5adb95dff62b
Revises: aa4072bc5965
Create Date: 2026-03-23 11:04:12.482715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adb95dff62b'
down_revision = 'aa4072bc5965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_control')
    # ### end Alembic commands ###
