"""Ajout index solde_revenu

Revision ID: 6f30250a9eb8
Revises: 2b67f3fc3140
Create Date: 2026-04-12 20:21:36.912252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f30250a9eb8'
down_revision = '2b67f3fc3140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_solde_revenu'), ['solde_revenu'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_solde_revenu'))

    # ### end Alembic commands ###
