"""Initial migration nova

Revision ID: 80615c9e5610
Revises: 
Create Date: 2026-02-26 06:05:52.900607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80615c9e5610'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investissement')
    op.drop_table('support_message')
    op.drop_table('vlog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vlog_pkey'))
    )
    op.create_table('support_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('support_message_pkey'))
    )
    op.create_table('investissement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenu_journalier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duree', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_debut', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dernier_paiement', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('investissement_pkey'))
    )
    # ### end Alembic commands ###
