"""empty message

Revision ID: aa4072bc5965
Revises: 9570da30ba27
Create Date: 2026-03-22 19:44:04.281190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4072bc5965'
down_revision = '9570da30ba27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('depot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
