"""empty message

Revision ID: b8e30ead3329
Revises: faf1a86f790c
Create Date: 2026-03-10 06:08:17.388560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e30ead3329'
down_revision = 'faf1a86f790c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_jeux', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('solde_jeux')

    # ### end Alembic commands ###
