"""empty message

Revision ID: c89e0ba2f123
Revises: 4851d64a40e1
Create Date: 2026-04-13 14:44:09.610563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89e0ba2f123'
down_revision = '4851d64a40e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.drop_column('type_retrait')

    with op.batch_alter_table('retrait_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_retrait', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        # ✅ ON GARDE L'AJOUT DES COLONNES
        batch_op.add_column(sa.Column('latitude', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_location_update', sa.DateTime(), nullable=True))
        
        # ❌ ON COMMENTE LES SUPPRESSIONS QUI POSENT PROBLÈME
        # batch_op.drop_constraint('user_email_key', type_='unique')
        # batch_op.drop_constraint('user_phone_key', type_='unique')
        # batch_op.drop_constraint('user_username_key', type_='unique')
        
        # ⚠️ ON COMMENTE AUSSI LES RE-CRÉATIONS D'INDEX POUR L'INSTANT
        # batch_op.drop_index(batch_op.f('ix_user_email'))
        # batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        # batch_op.drop_index(batch_op.f('ix_user_phone'))
        # batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        # batch_op.drop_index(batch_op.f('ix_user_username'))
        # batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_phone_key'), ['phone'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('last_location_update')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('retrait_points', schema=None) as batch_op:
        batch_op.drop_column('type_retrait')

    with op.batch_alter_table('retrait', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_retrait', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
