"""empty message

Revision ID: f3b51c616ccf
Revises: 6c7ea842594e
Create Date: 2026-04-07 11:07:41.612116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b51c616ccf'
down_revision = '6c7ea842594e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_rounds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('remaining_rounds')

    # ### end Alembic commands ###
